"""Smart trajectory tracker platform."""

from importlib import import_module

__all__ = [
    "Bounds2D",
    "ENUOrigin",
    "EnvironmentCRS",
    "EnvironmentModel",
    "FileReplayIngestionAdapter",
    "IngestionAdapter",
    "KNOWN_TERRAIN_PRESETS",
    "LandCoverClass",
    "LiveIngestionRunner",
    "MQTTIngestionAdapter",
    "LandCoverLayer",
    "MountainRange",
    "PathPlanner2D",
    "Plateau",
    "PlannerConfig",
    "PlannerRoute",
    "ReplayDocument",
    "RidgeLine",
    "ScenarioDefinition",
    "ScenarioOptions",
    "SensorVisibilityModel",
    "SimulationConfig",
    "SimulationResult",
    "TerrainFeature",
    "TerrainModel",
    "TrackerConfig",
    "TrackingService",
    "Valley",
    "VisibilityResult",
    "build_default_scenario",
    "build_replay_document",
    "load_replay_document",
    "load_environment_bundle",
    "run_simulation",
    "terrain_model_from_preset",
    "validate_replay_document",
    "write_environment_bundle",
    "wgs84_to_enu",
    "enu_to_wgs84",
    "WeatherModel",
    "weather_from_preset",
    "write_replay_document",
    "export_geojson",
    "export_czml",
    "export_foxglove",
    "build_scene_package",
    "build_scene_from_gis",
    "build_scene_from_replay",
    "load_scene_manifest",
    "validate_scene_manifest",
    "SimulationConstants",
    "SensorErrorConfig",
    "SensorModel",
    "sensor_error_config_from_preset",
    "build_target_trajectory",
    "FlightEnvelope",
    "BEHAVIOR_PRESETS",
]

_EXPORTS = {
    "Bounds2D": ("smart_tracker.environment", "Bounds2D"),
    "ENUOrigin": ("smart_tracker.coordinates", "ENUOrigin"),
    "EnvironmentCRS": ("smart_tracker.environment", "EnvironmentCRS"),
    "EnvironmentModel": ("smart_tracker.environment", "EnvironmentModel"),
    "FileReplayIngestionAdapter": ("smart_tracker.ingest", "FileReplayIngestionAdapter"),
    "IngestionAdapter": ("smart_tracker.ingest", "IngestionAdapter"),
    "KNOWN_TERRAIN_PRESETS": ("smart_tracker.terrain", "KNOWN_TERRAIN_PRESETS"),
    "LandCoverClass": ("smart_tracker.environment", "LandCoverClass"),
    "LiveIngestionRunner": ("smart_tracker.ingest", "LiveIngestionRunner"),
    "MQTTIngestionAdapter": ("smart_tracker.ingest", "MQTTIngestionAdapter"),
    "LandCoverLayer": ("smart_tracker.environment", "LandCoverLayer"),
    "MountainRange": ("smart_tracker.terrain", "MountainRange"),
    "PathPlanner2D": ("smart_tracker.planning", "PathPlanner2D"),
    "Plateau": ("smart_tracker.terrain", "Plateau"),
    "PlannerConfig": ("smart_tracker.planning", "PlannerConfig"),
    "PlannerRoute": ("smart_tracker.planning", "PlannerRoute"),
    "ReplayDocument": ("smart_tracker.replay", "ReplayDocument"),
    "RidgeLine": ("smart_tracker.terrain", "RidgeLine"),
    "ScenarioDefinition": ("smart_tracker.sim", "ScenarioDefinition"),
    "ScenarioOptions": ("smart_tracker.sim", "ScenarioOptions"),
    "SensorVisibilityModel": ("smart_tracker.environment", "SensorVisibilityModel"),
    "SimulationConfig": ("smart_tracker.sim", "SimulationConfig"),
    "SimulationResult": ("smart_tracker.sim", "SimulationResult"),
    "TerrainFeature": ("smart_tracker.terrain", "TerrainFeature"),
    "TerrainModel": ("smart_tracker.terrain", "TerrainModel"),
    "TrackerConfig": ("smart_tracker.service", "TrackerConfig"),
    "TrackingService": ("smart_tracker.service", "TrackingService"),
    "Valley": ("smart_tracker.terrain", "Valley"),
    "VisibilityResult": ("smart_tracker.environment", "VisibilityResult"),
    "build_default_scenario": ("smart_tracker.sim", "build_default_scenario"),
    "build_replay_document": ("smart_tracker.replay", "build_replay_document"),
    "load_replay_document": ("smart_tracker.replay", "load_replay_document"),
    "load_environment_bundle": ("smart_tracker.environment", "load_environment_bundle"),
    "run_simulation": ("smart_tracker.sim", "run_simulation"),
    "terrain_model_from_preset": ("smart_tracker.terrain", "terrain_model_from_preset"),
    "validate_replay_document": ("smart_tracker.replay", "validate_replay_document"),
    "write_environment_bundle": ("smart_tracker.environment", "write_environment_bundle"),
    "wgs84_to_enu": ("smart_tracker.coordinates", "wgs84_to_enu"),
    "enu_to_wgs84": ("smart_tracker.coordinates", "enu_to_wgs84"),
    "WeatherModel": ("smart_tracker.weather", "WeatherModel"),
    "weather_from_preset": ("smart_tracker.weather", "weather_from_preset"),
    "write_replay_document": ("smart_tracker.replay", "write_replay_document"),
    "export_geojson": ("smart_tracker.export", "export_geojson"),
    "export_czml": ("smart_tracker.export", "export_czml"),
    "export_foxglove": ("smart_tracker.export", "export_foxglove"),
    "build_scene_package": ("smart_tracker.scene", "build_scene_package"),
    "build_scene_from_gis": ("smart_tracker.scene", "build_scene_from_gis"),
    "build_scene_from_replay": ("smart_tracker.scene", "build_scene_from_replay"),
    "load_scene_manifest": ("smart_tracker.scene", "load_scene_manifest"),
    "validate_scene_manifest": ("smart_tracker.scene", "validate_scene_manifest"),
    "SimulationConstants": ("smart_tracker.config", "SimulationConstants"),
    "SensorErrorConfig": ("smart_tracker.sensor_models", "SensorErrorConfig"),
    "SensorModel": ("smart_tracker.sensor_models", "SensorModel"),
    "sensor_error_config_from_preset": ("smart_tracker.sensor_models", "sensor_error_config_from_preset"),
    "build_target_trajectory": ("smart_tracker.behaviors", "build_target_trajectory"),
    "FlightEnvelope": ("smart_tracker.behaviors", "FlightEnvelope"),
    "BEHAVIOR_PRESETS": ("smart_tracker.behaviors", "BEHAVIOR_PRESETS"),
}


def __getattr__(name: str) -> object:
    try:
        module_name, attr_name = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
