# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from smarttracker.v1 import tracker_pb2 as smarttracker_dot_v1_dot_tracker__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in smarttracker/v1/tracker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestFrame = channel.unary_unary(
                '/smarttracker.v1.TrackerService/IngestFrame',
                request_serializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameRequest.SerializeToString,
                response_deserializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameResponse.FromString,
                _registered_method=True)
        self.TrackStream = channel.stream_stream(
                '/smarttracker.v1.TrackerService/TrackStream',
                request_serializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameRequest.SerializeToString,
                response_deserializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameResponse.FromString,
                _registered_method=True)
        self.LatestFrame = channel.unary_unary(
                '/smarttracker.v1.TrackerService/LatestFrame',
                request_serializer=smarttracker_dot_v1_dot_tracker__pb2.LatestFrameRequest.SerializeToString,
                response_deserializer=smarttracker_dot_v1_dot_tracker__pb2.LatestFrameResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/smarttracker.v1.TrackerService/Reset',
                request_serializer=smarttracker_dot_v1_dot_tracker__pb2.ResetRequest.SerializeToString,
                response_deserializer=smarttracker_dot_v1_dot_tracker__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/smarttracker.v1.TrackerService/GetConfig',
                request_serializer=smarttracker_dot_v1_dot_tracker__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=smarttracker_dot_v1_dot_tracker__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/smarttracker.v1.TrackerService/Health',
                request_serializer=smarttracker_dot_v1_dot_tracker__pb2.HealthRequest.SerializeToString,
                response_deserializer=smarttracker_dot_v1_dot_tracker__pb2.HealthResponse.FromString,
                _registered_method=True)


class TrackerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFrame,
                    request_deserializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameRequest.FromString,
                    response_serializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameResponse.SerializeToString,
            ),
            'TrackStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TrackStream,
                    request_deserializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameRequest.FromString,
                    response_serializer=smarttracker_dot_v1_dot_tracker__pb2.IngestFrameResponse.SerializeToString,
            ),
            'LatestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestFrame,
                    request_deserializer=smarttracker_dot_v1_dot_tracker__pb2.LatestFrameRequest.FromString,
                    response_serializer=smarttracker_dot_v1_dot_tracker__pb2.LatestFrameResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=smarttracker_dot_v1_dot_tracker__pb2.ResetRequest.FromString,
                    response_serializer=smarttracker_dot_v1_dot_tracker__pb2.ResetResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=smarttracker_dot_v1_dot_tracker__pb2.GetConfigRequest.FromString,
                    response_serializer=smarttracker_dot_v1_dot_tracker__pb2.GetConfigResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=smarttracker_dot_v1_dot_tracker__pb2.HealthRequest.FromString,
                    response_serializer=smarttracker_dot_v1_dot_tracker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smarttracker.v1.TrackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smarttracker.v1.TrackerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarttracker.v1.TrackerService/IngestFrame',
            smarttracker_dot_v1_dot_tracker__pb2.IngestFrameRequest.SerializeToString,
            smarttracker_dot_v1_dot_tracker__pb2.IngestFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/smarttracker.v1.TrackerService/TrackStream',
            smarttracker_dot_v1_dot_tracker__pb2.IngestFrameRequest.SerializeToString,
            smarttracker_dot_v1_dot_tracker__pb2.IngestFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LatestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarttracker.v1.TrackerService/LatestFrame',
            smarttracker_dot_v1_dot_tracker__pb2.LatestFrameRequest.SerializeToString,
            smarttracker_dot_v1_dot_tracker__pb2.LatestFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarttracker.v1.TrackerService/Reset',
            smarttracker_dot_v1_dot_tracker__pb2.ResetRequest.SerializeToString,
            smarttracker_dot_v1_dot_tracker__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarttracker.v1.TrackerService/GetConfig',
            smarttracker_dot_v1_dot_tracker__pb2.GetConfigRequest.SerializeToString,
            smarttracker_dot_v1_dot_tracker__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarttracker.v1.TrackerService/Health',
            smarttracker_dot_v1_dot_tracker__pb2.HealthRequest.SerializeToString,
            smarttracker_dot_v1_dot_tracker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
